name: Run Python Script
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install python requirements
        shell: bash
        run: |
          # pip install transformers
          # pip install sentencepiece

      - name: Run script
        shell: bash
        run: python Scripts/questionGeneration.py 
      
      - name: Git Add & Commit
        uses: EndBug/add-and-commit@v9.0.1
        with:
          default_author: github_actions
